[env]
# You can set environment variables here

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
